In [1]:
from sklearn.datasets import make_moons

X, y = make_moons(n_samples=1000, noise=0.05)

In [2]:
from sklearn.mixture import GaussianMixture

gm=GaussianMixture(n_components=3, n_init=10)
gm.fit(X)

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=100,
                means_init=None, n_components=3, n_init=10,
                precisions_init=None, random_state=None, reg_covar=1e-06,
                tol=0.001, verbose=0, verbose_interval=10, warm_start=False,
                weights_init=None)

In [3]:
gm.weights_

array([0.2134423 , 0.21134304, 0.57521465])

In [4]:
gm.means_

array([[-0.72290883,  0.57459737],
       [ 1.72646859, -0.06745827],
       [ 0.50324129,  0.24810981]])

In [6]:
gm.covariances_

array([[[ 0.05946583,  0.0656511 ],
        [ 0.0656511 ,  0.09017585]],

       [[ 0.05962232,  0.06483126],
        [ 0.06483126,  0.08896527]],

       [[ 0.1574609 , -0.09090703],
        [-0.09090703,  0.2829022 ]]])

In [7]:
gm.converged_

True

In [8]:
gm.n_iter_

14

In [9]:
gm.predict(X)

array([2, 2, 2, 0, 2, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 1, 1, 0, 2, 0, 2,
       2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 0, 2, 2, 1,
       2, 0, 1, 2, 2, 2, 0, 2, 0, 2, 0, 0, 2, 1, 1, 2, 0, 2, 2, 2, 2, 2,
       0, 1, 2, 1, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 2,
       0, 2, 2, 2, 2, 0, 2, 2, 1, 2, 1, 2, 2, 0, 1, 0, 2, 2, 0, 1, 2, 2,
       2, 2, 1, 0, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 0, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 0, 2, 2, 0, 1, 2, 1, 2, 2, 0, 2, 2, 1, 2, 0, 0, 0,
       2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 1, 1,
       1, 2, 0, 0, 0, 2, 1, 1, 0, 2, 2, 2, 1, 2, 0, 1, 0, 1, 2, 2, 1, 2,
       0, 2, 1, 2, 2, 1, 2, 0, 2, 2, 0, 1, 1, 2, 2, 2, 0, 2, 2, 2, 2, 1,
       2, 0, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 1, 2, 2, 0, 0, 2, 0,
       0, 2, 2, 1, 2, 2, 2, 2, 0, 2, 1, 0, 2, 2, 2, 1, 2, 0, 2, 2, 1, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 0, 1, 2, 0, 2, 1, 2, 0, 0, 2, 2,

In [10]:
gm.predict_proba(X)

array([[1.28878628e-008, 1.27581558e-091, 9.99999987e-001],
       [9.95369124e-016, 3.51696224e-073, 1.00000000e+000],
       [2.47380792e-004, 1.15728651e-108, 9.99752619e-001],
       ...,
       [1.03119682e-015, 5.92547036e-071, 1.00000000e+000],
       [1.82953896e-024, 6.04321681e-056, 1.00000000e+000],
       [2.35175000e-030, 4.82502493e-048, 1.00000000e+000]])

In [11]:
X_new, y_new = gm.sample(6)

In [12]:
X_new

array([[ 1.91791373,  0.11157186],
       [ 1.68222255, -0.02933591],
       [ 1.46064823, -0.55613378],
       [ 1.61259609, -0.42551852],
       [ 1.71765159, -0.0527194 ],
       [ 1.47662845, -0.54098504]])

In [13]:
y_new

array([1, 1, 1, 1, 1, 2])

In [14]:
gm.score_samples(X)

array([-1.68069943e+00, -1.78408915e+00, -1.94780909e+00, -3.17671653e-01,
       -1.56918478e+00, -4.01915995e-01, -1.27914595e+00, -1.72619608e+00,
       -1.16315522e+00, -2.29208400e+00, -1.35411221e+00, -4.27210410e-01,
       -1.59539659e+00, -1.72934582e+00, -1.76509782e+00, -4.81947790e-01,
       -8.26377448e-01, -2.59417658e-01, -5.99270440e-01, -1.53141002e+00,
       -1.51858879e+00, -2.02786952e+00, -1.09805045e+00, -1.49220649e+00,
       -2.04743007e+00, -3.77861662e-01, -1.54695914e+00, -1.91119847e+00,
       -1.44927431e+00, -1.53749597e+00, -1.39642716e+00, -1.71738800e+00,
       -1.00297308e+00, -1.51031132e+00, -1.26110370e+00, -1.87124239e+00,
       -1.61257517e+00, -1.57225110e+00, -1.68276867e+00, -1.95923806e+00,
       -9.64127448e-01, -1.54548236e+00, -1.27072736e+00, -4.17136445e-01,
       -1.89318401e+00, -7.79601463e-01, -6.70122196e-01, -1.57839560e+00,
       -1.71348269e+00, -2.12406024e+00, -7.41766625e-01, -2.12797303e+00,
       -1.81530741e+00, -

In [15]:
#Anomaly detection
import numpy as np

densities=gm.score_samples(X)
density_threshold= np.percentile(densities, 4)
anomalies=X[densities<density_threshold]

In [16]:
anomalies

array([[-0.88279343,  0.67272047],
       [ 1.09033818, -0.54811318],
       [-0.06971977,  1.06897739],
       [ 1.93857245,  0.453119  ],
       [ 1.92917621,  0.47804257],
       [ 1.92583872,  0.42865468],
       [-0.15853808,  0.96041331],
       [ 2.07460176,  0.5230483 ],
       [ 1.96305096,  0.49076863],
       [ 2.00300657,  0.50000401],
       [ 1.03388401, -0.57381414],
       [-0.12645015,  1.11105871],
       [-0.94772581,  0.06578385],
       [-0.1970167 ,  0.93096945],
       [ 1.15103622, -0.39545933],
       [ 1.11302479, -0.5167426 ],
       [-0.97020687,  0.03299233],
       [ 1.90714142,  0.5117593 ],
       [-0.92202242, -0.01979259],
       [ 1.96726423,  0.46251371],
       [-0.97161275, -0.10813241],
       [ 1.10370174, -0.52514135],
       [-0.94216677,  0.05242471],
       [-0.9967965 , -0.1028721 ],
       [ 1.95069376,  0.48890485],
       [-0.09164063,  1.00724856],
       [-0.11265569,  1.06900023],
       [ 1.10147016, -0.52982344],
       [ 1.01002415,

In [17]:
anomalies.shape

(40, 2)

In [18]:
gm.bic(X)

2794.8252648116445

In [19]:
gm.aic(X)

2711.393425068948

In [20]:
from sklearn.mixture import BayesianGaussianMixture

bgm=BayesianGaussianMixture(n_components=10, n_init=10)
bgm.fit(X)
bgm.weights_

array([1.32043064e-01, 1.12255553e-01, 1.53642053e-01, 1.85109732e-01,
       1.34098692e-01, 1.61078385e-01, 1.00683196e-03, 1.20669183e-01,
       8.84630337e-05, 8.04208532e-06])

In [21]:
np.round(bgm.weights_, 2)

array([0.13, 0.11, 0.15, 0.19, 0.13, 0.16, 0.  , 0.12, 0.  , 0.  ])

In [24]:
for i in range(1,11):
    gm=GaussianMixture(n_components=i, n_init=10)
    gm.fit(X)
    print(gm.bic(X))

3796.005189457304
3489.6604902143317
2794.8372618714143
2320.9069079290684
2024.3123529726288
1501.4461284202027
1290.7757590918593
1180.303869836847
1123.6622754394416
1089.6097330363623


In [26]:
for i in range(1,11):
    gm=GaussianMixture(n_components=i, n_init=10)
    gm.fit(X)
    print(gm.aic(X))

3771.4664130623933
3435.675182145528
2711.393425068948
2208.028536512479
1881.9874498821468
1329.7426997731477
1089.3102303525498
949.5999257998861
859.6395984616938
800.1250186317528
