In [ ]:
from sklearn.cluster import KMeans

k=5
kmeans=KMeans(n_clusters=k)
y_pred=kmeans.fit_predict(X)

In [ ]:
y_pred

In [ ]:
y_pred is kmeans.labels_

In [ ]:
kmeans.cluster_centers_

In [ ]:
X_new= np.array([[0,2], [3,2], [-3,3],[-3, 2.5]])

In [ ]:
kmeans.predict(X_new) #array([1, 1, 2, 2])

In [ ]:
kmeans.transform(X_new) #distance from each instance to every centroid

In [ ]:
kmeans.inertia_

In [ ]:
kmeans.score(X)

In [ ]:
from sklearn.cluster import MiniBatchKMeans
minibatch_kmeans=MiniBatchKMeans(n_clusters=5)
minibatch_kmeans.fit(X)

In [ ]:
from sklearn.metrics import silhouette_score
silhouette_score(X, kmeans.labels_)

In [2]:
import os
from matplotlib.image import imread
image=imread(os.path.join("ladybug.png"))
image.shape #height 553, width 800, colors 3(RGB)

(533, 800, 3)

In [3]:
image

array([[[0.09803922, 0.11372549, 0.00784314],
        [0.09411765, 0.10980392, 0.00392157],
        [0.09411765, 0.11372549, 0.        ],
        ...,
        [0.22352941, 0.4117647 , 0.08235294],
        [0.21960784, 0.40392157, 0.08627451],
        [0.20392157, 0.3882353 , 0.07450981]],

       [[0.09411765, 0.10980392, 0.00392157],
        [0.09019608, 0.10588235, 0.        ],
        [0.09019608, 0.10588235, 0.        ],
        ...,
        [0.23529412, 0.42352942, 0.08627451],
        [0.23137255, 0.41568628, 0.09803922],
        [0.21568628, 0.4       , 0.08627451]],

       [[0.09019608, 0.10588235, 0.00784314],
        [0.08627451, 0.10196079, 0.00392157],
        [0.08627451, 0.10196079, 0.        ],
        ...,
        [0.25882354, 0.44705883, 0.10980392],
        [0.24705882, 0.43529412, 0.10588235],
        [0.22745098, 0.4117647 , 0.09411765]],

       ...,

       [[0.05490196, 0.07058824, 0.00392157],
        [0.05490196, 0.07058824, 0.00392157],
        [0.05098039, 0

In [4]:
X=image.reshape(-1, 3)

In [5]:
X

array([[0.09803922, 0.11372549, 0.00784314],
       [0.09411765, 0.10980392, 0.00392157],
       [0.09411765, 0.11372549, 0.        ],
       ...,
       [0.03921569, 0.22745098, 0.        ],
       [0.01960784, 0.20392157, 0.        ],
       [0.00784314, 0.1882353 , 0.        ]], dtype=float32)

In [7]:
from sklearn.cluster import KMeans

In [8]:
kmeans=KMeans(n_clusters=8)

In [9]:
k_clu=kmeans.fit(X)

In [10]:
segmented_img=k_clu.cluster_centers_[kmeans.labels_]

In [11]:
segmented_img=segmented_img.reshape(image.shape)

In [12]:
segmented_img

array([[[0.02103791, 0.10643876, 0.00561932],
        [0.02103791, 0.10643876, 0.00561932],
        [0.02103791, 0.10643876, 0.00561932],
        ...,
        [0.20925015, 0.37658414, 0.05342072],
        [0.20925015, 0.37658414, 0.05342072],
        [0.20925015, 0.37658414, 0.05342072]],

       [[0.02103791, 0.10643876, 0.00561932],
        [0.02103791, 0.10643876, 0.00561932],
        [0.02103791, 0.10643876, 0.00561932],
        ...,
        [0.20925015, 0.37658414, 0.05342072],
        [0.20925015, 0.37658414, 0.05342072],
        [0.20925015, 0.37658414, 0.05342072]],

       [[0.02103791, 0.10643876, 0.00561932],
        [0.02103791, 0.10643876, 0.00561932],
        [0.02103791, 0.10643876, 0.00561932],
        ...,
        [0.20925015, 0.37658414, 0.05342072],
        [0.20925015, 0.37658414, 0.05342072],
        [0.20925015, 0.37658414, 0.05342072]],

       ...,

       [[0.02103791, 0.10643876, 0.00561932],
        [0.02103791, 0.10643876, 0.00561932],
        [0.02103791, 0