In [1]:
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons

X, y=make_moons(n_samples=1000, noise=0.05)
dbscan=DBSCAN(eps=0.05, min_samples=5)
dbscan.fit(X)

DBSCAN(algorithm='auto', eps=0.05, leaf_size=30, metric='euclidean',
       metric_params=None, min_samples=5, n_jobs=None, p=None)

In [2]:
X

array([[ 0.34409404, -0.19400922],
       [ 0.06418796,  0.06977509],
       [ 1.68911059, -0.17114656],
       ...,
       [-0.78240403,  0.69710446],
       [ 0.97691207,  0.1397105 ],
       [-0.99108127,  0.25636127]])

In [3]:
y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,

In [4]:
y.shape

(1000,)

In [5]:
dbscan.labels_

array([ 0,  1,  2, 13,  1,  3,  4,  1,  2, -1,  6,  4,  2,  4,  4,  5,  5,
        0,  0,  2,  0,  3, -1,  2,  9,  4,  4,  3,  5,  0,  4,  4, -1,  4,
        3,  3,  0,  4,  5,  4,  5,  2,  5,  1,  0,  6,  5,  7,  0,  8,  7,
        2,  4,  9,  3,  1, 10,  4,  3,  4,  9,  2,  3,  4,  5,  8,  4,  0,
        4,  2,  0,  0,  0,  9,  4,  4,  0,  5,  4,  4,  9,  4, -1,  0,  4,
        9, -1,  4,  4,  4,  4,  4,  3,  0,  2,  4,  0,  0, -1,  3,  4,  7,
        4,  2,  4,  9,  4,  4,  0,  4,  2,  7, 10,  0, 13,  0, 10, 12,  5,
       -1,  4, -1,  7,  9,  0, -1,  5,  4,  0,  2,  7,  4,  0,  4,  4,  3,
        4,  4,  4,  4,  4,  3,  1,  4,  1,  0,  3,  0,  1,  7,  4,  4,  3,
        4,  4,  4,  0,  4, 11,  7,  4, -1,  0,  4,  0,  5,  2,  0,  9,  5,
        7,  1,  1,  4,  0,  5,  8,  4,  4,  4,  4, 10,  4,  3,  4,  7, 10,
        7,  4,  4,  4,  1,  2,  3, 10,  9,  4,  4,  4,  4, 11,  4,  4,  0,
        0, -1, -1,  1,  6,  0,  4,  4,  1,  5,  6,  4, -1,  0,  0, 12,  4,
       10, -1,  4,  4,  2

In [6]:
dbscan.core_sample_indices_

array([  0,   1,   2,   5,   6,   7,   8,  11,  12,  13,  14,  15,  16,
        17,  18,  19,  20,  21,  23,  26,  27,  28,  29,  30,  31,  33,
        34,  35,  36,  37,  39,  40,  41,  42,  43,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  72,  73,  74,  75,  76,  78,
        79,  80,  83,  84,  85,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97,  99, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110, 111, 112, 113, 116, 118, 120, 123, 124, 126, 127, 128, 129,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 143, 144,
       145, 146, 147, 150, 151, 152, 153, 154, 155, 156, 157, 158, 162,
       164, 165, 166, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
       193, 194, 196, 197, 198, 199, 201, 203, 207, 208, 211, 212, 213,
       214, 215, 220, 221, 224, 225, 226, 227, 228, 229, 230, 23

In [7]:
dbscan.components_

array([[ 0.34409404, -0.19400922],
       [ 0.06418796,  0.06977509],
       [ 1.68911059, -0.17114656],
       ...,
       [-0.78240403,  0.69710446],
       [ 0.97691207,  0.1397105 ],
       [-0.99108127,  0.25636127]])

In [8]:
dbscan.components_.shape

(804, 2)

In [9]:
dbscan.core_sample_indices_.shape

(804,)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=50)
knn.fit(dbscan.components_, dbscan.labels_[dbscan.core_sample_indices_])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=50, p=2,
                     weights='uniform')

In [14]:
import numpy as np
X_new =np.array([[-0.5,0],[0,0.5],[1,-0.1],[2,1]])

In [15]:
knn.predict(X_new)

array([4, 1, 5, 9], dtype=int64)

In [16]:
knn.predict_proba(X_new)

array([[0.  , 0.1 , 0.  , 0.  , 0.86, 0.  , 0.02, 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.02, 0.  ],
       [0.  , 0.52, 0.  , 0.  , 0.  , 0.  , 0.48, 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  ],
       [0.28, 0.  , 0.  , 0.  , 0.  , 0.72, 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.44, 0.  , 0.56, 0.  ,
        0.  , 0.  , 0.  ]])

In [19]:
y_dist, y_pred_idx=knn.kneighbors(X_new, n_neighbors=1)

In [20]:
y_dist

array([[0.44428845],
       [0.01734079],
       [0.10536458],
       [0.54836489]])

In [21]:
y_pred_idx #Probably the indices of the nearest neighboring instance

array([[618],
       [630],
       [577],
       [ 69]], dtype=int64)

In [22]:
y_pred =dbscan.labels_[dbscan.core_sample_indices_][y_pred_idx]
y_pred[y_dist>0.2]=-1
y_pred.ravel()

array([-1,  6,  5, -1], dtype=int64)