In [2]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing=fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data, housing.target)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full)

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_valid=scaler.transform(X_valid)
X_test=scaler.transform(X_test)

In [3]:
X_train.shape

(11610, 8)

In [4]:
X_train.shape[1:]

(8,)

In [5]:
X_train

array([[-1.14378077, -0.20428138, -0.35036901, ...,  0.09966861,
        -0.7940327 ,  1.05301358],
       [-0.92374925,  0.19121402, -0.23066809, ...,  0.02165969,
        -0.54229841,  1.20716327],
       [ 0.77077172, -1.07437127,  0.28590708, ..., -0.00536432,
        -0.73343   ,  1.20716327],
       ...,
       [ 0.41066764, -1.46986668,  0.32267486, ..., -0.02365992,
         0.80494625, -0.50837361],
       [-0.83108505,  0.82400667, -0.72304745, ...,  0.16844592,
        -0.74741524,  0.69001592],
       [ 0.00320769,  1.37770024, -0.00550385, ..., -0.02772224,
        -0.72410651,  0.73476905]])

In [8]:
from tensorflow import keras
model=keras.models.Sequential([
    keras.layers.Dense(30, activation="relu", input_shape=X_train.shape[1:]),
    keras.layers.Dense(1)
])

model.compile(loss="mean_squared_error", optimizer="sgd")

history=model.fit(X_train, y_train, epochs=20, validation_data=(X_valid, y_valid))

C:\Users\keonhi\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\keonhi\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\keonhi\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\keonhi\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: P

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Train on 11610 samples, validate on 3870 samples
Epoch 1/20
11610/11610 [==============================] - 3s 246us/sample - loss: 1.1773 - val_loss: 0.5433
Epoch 2/20
11610/11610 [==============================] - 1s 45us/sample - loss: 0.5153 - val_loss: 0.4815
Epoch 3/20
11610/11610 [==============================] - 1s 48us/sample - loss: 0.4848 - val_loss: 0.4903
Epoch 4/20
11610/11610 [==============================] - 1s 48us/sample - loss: 0.4661 - val_loss: 0.4477
Epoch 5/20
11610/11610 [==============================] - 1s 50us/sample - loss: 0.4486 - val_loss: 0.4427
Epoch 6/20
11610/11610 [==============================] - 1s 48us/sample - loss: 0.4389 - val_loss: 0.4275
Epoch 7/20
11610/11610 [==============================] - 1s 70us/sample - loss: 0.4304 - val_loss: 0.4211
Epoch 8/20
11610/11610 [==============================] - 1s 48us/sample - loss: 0.

In [10]:
mse=model.evaluate(X_test, y_test)

5160/5160 [==============================] - 0s 29us/sample - loss: 0.3773


In [11]:
X_new = X_train[:3]

In [12]:
X_new

array([[-1.14378077, -0.20428138, -0.35036901,  0.04772891,  0.82593701,
         0.09966861, -0.7940327 ,  1.05301358],
       [-0.92374925,  0.19121402, -0.23066809, -0.18383662, -1.05420129,
         0.02165969, -0.54229841,  1.20716327],
       [ 0.77077172, -1.07437127,  0.28590708, -0.07029363, -0.44579699,
        -0.00536432, -0.73343   ,  1.20716327]])

In [13]:
y_pred=model.predict(X_new)

In [14]:
y_pred

array([[0.7256104],
       [0.6043854],
       [1.7835953]], dtype=float32)

In [15]:
model.predict_proba(X_new)

array([[0.7256104],
       [0.6043854],
       [1.7835953]], dtype=float32)

In [16]:
#Sequential API
#model=keras.models.Sequential([ keras.layers.Dense(30, activation='relu', input_shape=X_train.shape[1:]), ... ])
#model.compile(loss="mean_squared_error", optimizer="sgd")
#history=model.fit(X_train, y_train,   epochs=20, validation_data=(X_valid, y_valid))

In [28]:
#Wide&Deep neural network
#Concatenate

input_ = keras.layers.Input(shape=X_train.shape[1:])
hidden1= keras.layers.Dense(30, activation="relu")(input_)
hidden2= keras.layers.Dense(30, activation="relu")(hidden1)
concat= keras.layers.Concatenate()([hidden2, input_])
output_ = keras.layers.Dense(1)(concat)
model=keras.Model(inputs=[input_], outputs=[output_])

In [38]:
inputB = keras.layers.Input(shape=(6,), name ="deep_input") #name is not necessary
hidden1 = keras.layers.Dense(30, activation="relu")(inputB)
hidden2 = keras.layers.Dense(30, activation="relu")(hidden1)
inputA = keras.layers.Input(shape=5, name="wide_input") #name is not necessary
concat = keras.layers.Concatenate()([inputA, hidden2]) 

In [39]:
output = keras.layers.Dense(1)(concat)

In [40]:
model =keras.Model(inputs=[inputA, inputB], outputs=[output])

In [43]:
model.compile(loss="mean_squared_error", optimizer="sgd")

In [46]:
X_train_A = X_train[:,:5]
X_train_B = X_train[:, 2:]

model.fit((X_train_A,X_train_B), y_train, epochs=20)

Epoch 1/20
11610/11610 [==============================] - 1s 66us/sample - loss: 1.1986
Epoch 2/20
11610/11610 [==============================] - 1s 48us/sample - loss: 0.5627
Epoch 3/20
11610/11610 [==============================] - 1s 47us/sample - loss: 0.5124
Epoch 4/20
11610/11610 [==============================] - 1s 47us/sample - loss: 0.4823
Epoch 5/20
11610/11610 [==============================] - 1s 48us/sample - loss: 0.4618
Epoch 6/20
11610/11610 [==============================] - 1s 48us/sample - loss: 0.4767
Epoch 7/20
11610/11610 [==============================] - 1s 47us/sample - loss: 0.4339
Epoch 8/20
11610/11610 [==============================] - 1s 48us/sample - loss: 0.4245
Epoch 9/20
11610/11610 [==============================] - 1s 47us/sample - loss: 0.4137
Epoch 10/20
11610/11610 [==============================] - 1s 47us/sample - loss: 0.4086
Epoch 11/20
11610/11610 [==============================] - 1s 47us/sample - loss: 0.4013
Epoch 12/20
11610/11610 [=====

In [48]:
X_train_A = X_train[:,:5]
X_train_B = X_train[:, 2:]
X_valid_A = X_valid[:,:5]
X_valid_B = X_valid[:, 2:]

history=model.fit((X_train_A,X_train_B), y_train, epochs=20, validation_data=((X_valid_A, X_valid_B), y_valid))

Train on 11610 samples, validate on 3870 samples
Epoch 1/20
11610/11610 [==============================] - 1s 60us/sample - loss: 0.3405 - val_loss: 0.3399
Epoch 2/20
11610/11610 [==============================] - 1s 59us/sample - loss: 0.3366 - val_loss: 0.3412
Epoch 3/20
11610/11610 [==============================] - 1s 58us/sample - loss: 0.3398 - val_loss: 0.3510
Epoch 4/20
11610/11610 [==============================] - 1s 58us/sample - loss: 0.3360 - val_loss: 0.3449
Epoch 5/20
11610/11610 [==============================] - 1s 58us/sample - loss: 0.3341 - val_loss: 0.3537
Epoch 6/20
11610/11610 [==============================] - 1s 58us/sample - loss: 0.3391 - val_loss: 0.3357
Epoch 7/20
11610/11610 [==============================] - 1s 59us/sample - loss: 0.3344 - val_loss: 0.3825
Epoch 8/20
11610/11610 [==============================] - 1s 58us/sample - loss: 0.3332 - val_loss: 0.3399
Epoch 9/20
11610/11610 [==============================] - 1s 58us/sample - loss: 0.3350 - val_l

In [49]:
X_test_A, X_test_B = X_test[:, :5], X_test[:, 2:]
mse_test = model.evaluate((X_test_A, X_test_B), y_test)

5160/5160 [==============================] - 0s 35us/sample - loss: 0.3159


In [50]:
X_new_A, X_new_B = X_new[:, :5], X_new[:,2:]
y_pred=model.predict((X_new_A, X_new_B))

In [51]:
y_pred

array([[0.8988588],
       [0.9194963],
       [1.7580698]], dtype=float32)

In [52]:
model.compile(loss="mean_squared_error", optimizer=keras.optimizers.SGD(lr=1e-3))

In [53]:
inputB = keras.layers.Input(shape=(6,), name ="deep_input") #name is not necessary
hidden1 = keras.layers.Dense(30, activation="relu")(inputB)
hidden2 = keras.layers.Dense(30, activation="relu")(hidden1)
inputA = keras.layers.Input(shape=5, name="wide_input") #name is not necessary
concat = keras.layers.Concatenate()([inputA, hidden2]) 
output = keras.layers.Dense(1)(concat)
model =keras.Model(inputs=[inputA, inputB], outputs=[output])

In [54]:
model.compile(loss="mean_squared_error", optimizer="sgd")

In [55]:
history=model.fit((X_train_A,X_train_B), y_train, epochs=20, validation_data=((X_valid_A, X_valid_B), y_valid))

Train on 11610 samples, validate on 3870 samples
Epoch 1/20
11610/11610 [==============================] - 1s 85us/sample - loss: 0.9019 - val_loss: 0.5430
Epoch 2/20
11610/11610 [==============================] - 1s 60us/sample - loss: 0.5322 - val_loss: 0.5665
Epoch 3/20
11610/11610 [==============================] - 1s 59us/sample - loss: 0.5089 - val_loss: 0.4863
Epoch 4/20
11610/11610 [==============================] - 1s 58us/sample - loss: 0.4847 - val_loss: 0.4745
Epoch 5/20
11610/11610 [==============================] - 1s 58us/sample - loss: 0.4724 - val_loss: 0.4604
Epoch 6/20
11610/11610 [==============================] - 1s 60us/sample - loss: 0.4736 - val_loss: 0.4513
Epoch 7/20
11610/11610 [==============================] - 1s 59us/sample - loss: 0.4460 - val_loss: 0.4369
Epoch 8/20
11610/11610 [==============================] - 1s 58us/sample - loss: 0.4350 - val_loss: 0.4270
Epoch 9/20
11610/11610 [==============================] - 1s 58us/sample - loss: 0.4225 - val_l

In [56]:
mse_test = model.evaluate((X_test_A, X_test_B), y_test)
y_pred=model.predict((X_new_A, X_new_B))
y_pred

5160/5160 [==============================] - 0s 28us/sample - loss: 0.3318


array([[0.7566462 ],
       [0.80276746],
       [1.6456962 ]], dtype=float32)

In [57]:
inputB= keras.layers.Input(shape=6, name="deep_input")
hidden1= keras.layers.Dense(30, activation="relu")(inputB)
hidden2= keras.layers.Dense(30, activation="relu")(hidden1)
inputA= keras.layers.Input(shape=5, name="wide_input")
concat= keras.layers.Concatenate()([inputA, hidden2])
aux_output= keras.layers.Dense(1)(hidden2)
output=keras.layers.Dense(1)(concat)

In [58]:
model2= keras.Model(inputs=[inputA, inputB], outputs=[output, aux_output])

In [61]:
model2.compile(loss="mean_squared_error", optimizer=keras.optimizers.SGD(lr=1e-3))

In [63]:
model2.fit((X_train_A, X_train_B), (y_train, y_train))

11610/11610 [==============================] - 1s 76us/sample - loss: 4.3399 - dense_36_loss: 2.0635 - dense_35_loss: 2.2757


In [64]:
model2.fit((X_train_A, X_train_B), (y_train, y_train), epochs=20,
          validation_data= ((X_valid_A, X_valid_B), (y_valid, y_valid)))

Train on 11610 samples, validate on 3870 samples
Epoch 1/20
11610/11610 [==============================] - 1s 86us/sample - loss: 2.2832 - dense_36_loss: 0.9434 - dense_35_loss: 1.3402 - val_loss: 1.9808 - val_dense_36_loss: 0.7842 - val_dense_35_loss: 1.1968
Epoch 2/20
11610/11610 [==============================] - 1s 79us/sample - loss: 1.9567 - dense_36_loss: 0.7649 - dense_35_loss: 1.1921 - val_loss: 1.7461 - val_dense_36_loss: 0.6799 - val_dense_35_loss: 1.0661
Epoch 3/20
11610/11610 [==============================] - 1s 79us/sample - loss: 1.7333 - dense_36_loss: 0.6780 - dense_35_loss: 1.0549 - val_loss: 1.5514 - val_dense_36_loss: 0.6146 - val_dense_35_loss: 0.9368
Epoch 4/20
11610/11610 [==============================] - 1s 79us/sample - loss: 1.5528 - dense_36_loss: 0.6202 - dense_35_loss: 0.9326 - val_loss: 1.4084 - val_dense_36_loss: 0.5723 - val_dense_35_loss: 0.8359
Epoch 5/20
11610/11610 [==============================] - 1s 79us/sample - loss: 1.4220 - dense_36_loss: 0.

In [66]:
model2.compile(loss=["mse", "mse"], loss_weights=[0.9, 0.1], optimizer="sgd")

In [67]:
model2.fit((X_train_A, X_train_B), (y_train, y_train), epochs=20,
          validation_data= ((X_valid_A, X_valid_B), (y_valid, y_valid)))

Train on 11610 samples, validate on 3870 samples
Epoch 1/20
11610/11610 [==============================] - 1s 94us/sample - loss: 0.4734 - dense_36_loss: 0.4584 - dense_35_loss: 0.6079 - val_loss: 0.4616 - val_dense_36_loss: 0.4467 - val_dense_35_loss: 0.5948
Epoch 2/20
11610/11610 [==============================] - 1s 81us/sample - loss: 0.4688 - dense_36_loss: 0.4539 - dense_35_loss: 0.6033 - val_loss: 0.5425 - val_dense_36_loss: 0.5334 - val_dense_35_loss: 0.6223
Epoch 3/20
11610/11610 [==============================] - 1s 82us/sample - loss: 0.6080 - dense_36_loss: 0.6042 - dense_35_loss: 0.6413 - val_loss: 0.4785 - val_dense_36_loss: 0.4638 - val_dense_35_loss: 0.6117
Epoch 4/20
11610/11610 [==============================] - 1s 82us/sample - loss: 0.4883 - dense_36_loss: 0.4732 - dense_35_loss: 0.6240 - val_loss: 0.4603 - val_dense_36_loss: 0.4447 - val_dense_35_loss: 0.5996
Epoch 5/20
11610/11610 [==============================] - 1s 81us/sample - loss: 0.4661 - dense_36_loss: 0.

In [70]:
total_loss, main_loss, aux_loss = model2.evaluate([X_test_A, X_test_B], [y_test, y_test])

5160/5160 [==============================] - 0s 42us/sample - loss: 0.3499 - dense_36_loss: 0.3370 - dense_35_loss: 0.4633


In [72]:
y_pred_main, y_pred_aux = model2.predict([X_new_A, X_new_B])

In [73]:
y_pred_main

array([[0.8307997],
       [0.8642037],
       [1.7015984]], dtype=float32)

In [74]:
y_pred_aux

array([[1.0334437],
       [1.2010483],
       [1.3025247]], dtype=float32)

In [78]:
#Subclassing API
class WideAndDeepModel(keras.Model):
    def __init__ (self, units=30, activation="relu", **kwargs):
        super().__init__(**kwargs) #handles stardard args (e.g., name)
        self.hidden1=keras.layers.Dense(units, activation=activation)
        self.hidden2=keras.layers.Dense(units, activation=activation)
        self.main_output=keras.layers.Dense(1)
        self.aux_output=keras.layers.Dense(1)
        
    def call(self, inputs):
        inputA, inputB = inputs
        hidden1=self.hidden1(inputB)
        hidden2=self.hidden2(hidden1)
        concat=keras.layers.Concatenate()([inputA, hidden2])
        main_output= self.main_output(concat)
        aux_output= self.aux_output(hidden2)
        return main_output, aux_output

model=WideAndDeepModel()

In [79]:
#The special syntax **kwargs in function definitions in python is used to pass a keyworded, variable-length argument list.
#We use the name kwargs with the double star. 
#The reason is because the double star allows us to pass through keyword arguments (and any number of them).

In [80]:
model2.save("functional_api.h5")

In [83]:
model3 = keras.models.load_model("functional_api.h5")

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [84]:
model3

In [86]:
model3.fit([X_train_A,X_train_B], [y_train, y_train])

11610/11610 [==============================] - 1s 75us/sample - loss: 0.4809 - dense_36_loss: 0.4736 - dense_35_loss: 0.5467


In [87]:
model3.predict([X_new_A, X_new_B])

[array([[0.7499379 ],
        [0.73624384],
        [1.6314163 ]], dtype=float32),
 array([[1.0310099],
        [1.2155894],
        [1.2898754]], dtype=float32)]

In [96]:
#fit() method accepts callbacks argument that lets you specify a list of objects that Keras will call 
#at the start and end of training, at the start and end of each epoch, and even before and after processing each batch.

checkpoint_cb=keras.callbacks.ModelCheckpoint("keras_model.h5")
history=model2.fit([X_train_A, X_train_B], [y_train, y_train], epochs=10, callbacks=[checkpoint_cb]) #callbacks=[], must be a list

Epoch 1/10
11610/11610 [==============================] - 1s 72us/sample - loss: 0.3594 - dense_36_loss: 0.3486 - dense_35_loss: 0.4554
Epoch 2/10
11610/11610 [==============================] - 1s 70us/sample - loss: 0.3968 - dense_36_loss: 0.3894 - dense_35_loss: 0.4644
Epoch 3/10
11610/11610 [==============================] - 1s 68us/sample - loss: 0.3657 - dense_36_loss: 0.3555 - dense_35_loss: 0.4574
Epoch 4/10
11610/11610 [==============================] - 1s 72us/sample - loss: 0.3577 - dense_36_loss: 0.3474 - dense_35_loss: 0.4499
Epoch 5/10
11610/11610 [==============================] - 1s 72us/sample - loss: 0.3552 - dense_36_loss: 0.3450 - dense_35_loss: 0.4465
Epoch 6/10
11610/11610 [==============================] - 1s 71us/sample - loss: 0.3530 - dense_36_loss: 0.3429 - dense_35_loss: 0.4435
Epoch 7/10
11610/11610 [==============================] - 1s 72us/sample - loss: 0.3508 - dense_36_loss: 0.3410 - dense_35_loss: 0.4379
Epoch 8/10
11610/11610 [========================

In [102]:
checkpoint_cb= keras.callbacks.ModelCheckpoint("keras_model.h5", save_best_only=True)
history=model2.fit([X_train_A, X_train_B], [y_train, y_train], 
                   validation_data=([X_valid_A, X_valid_B], [y_valid, y_valid]),
                   epochs=10, callbacks=[checkpoint_cb])

#only save when the model's performance on validation set is best so far.

Train on 11610 samples, validate on 3870 samples
Epoch 1/10
11610/11610 [==============================] - 1s 84us/sample - loss: 0.3501 - dense_36_loss: 0.3410 - dense_35_loss: 0.4321 - val_loss: 0.3421 - val_dense_36_loss: 0.3326 - val_dense_35_loss: 0.4284
Epoch 2/10
11610/11610 [==============================] - 1s 83us/sample - loss: 0.3474 - dense_36_loss: 0.3382 - dense_35_loss: 0.4295 - val_loss: 0.3490 - val_dense_36_loss: 0.3397 - val_dense_35_loss: 0.4329
Epoch 3/10
11610/11610 [==============================] - 1s 82us/sample - loss: 0.3464 - dense_36_loss: 0.3374 - dense_35_loss: 0.4267 - val_loss: 0.3599 - val_dense_36_loss: 0.3504 - val_dense_35_loss: 0.4467
Epoch 4/10
11610/11610 [==============================] - 1s 83us/sample - loss: 0.3448 - dense_36_loss: 0.3359 - dense_35_loss: 0.4259 - val_loss: 0.3420 - val_dense_36_loss: 0.3326 - val_dense_35_loss: 0.4257
Epoch 5/10
11610/11610 [==============================] - 1s 83us/sample - loss: 0.3447 - dense_36_loss: 0.

In [103]:
history=model2.fit([X_train_A, X_train_B], [y_train, y_train])

11610/11610 [==============================] - 1s 69us/sample - loss: 0.3418 - dense_36_loss: 0.3337 - dense_35_loss: 0.4164


In [107]:
earlystopping_cb = keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)
history=model2.fit([X_train_A, X_train_B], [y_train, y_train], epochs= 100,
                  validation_data=([X_valid_A, X_valid_B], [y_valid, y_valid]),
                  callbacks=[checkpoint_cb, earlystopping_cb]
                  )

Train on 11610 samples, validate on 3870 samples
Epoch 1/100
11610/11610 [==============================] - 1s 92us/sample - loss: 0.3396 - dense_36_loss: 0.3315 - dense_35_loss: 0.4145 - val_loss: 0.3339 - val_dense_36_loss: 0.3251 - val_dense_35_loss: 0.4122
Epoch 2/100
11610/11610 [==============================] - 1s 89us/sample - loss: 0.3381 - dense_36_loss: 0.3301 - dense_35_loss: 0.4120 - val_loss: 0.3495 - val_dense_36_loss: 0.3419 - val_dense_35_loss: 0.4172
Epoch 3/100
11610/11610 [==============================] - 1s 85us/sample - loss: 0.3386 - dense_36_loss: 0.3306 - dense_35_loss: 0.4106 - val_loss: 0.3401 - val_dense_36_loss: 0.3313 - val_dense_35_loss: 0.4195
Epoch 4/100
11610/11610 [==============================] - 1s 82us/sample - loss: 0.3402 - dense_36_loss: 0.3321 - dense_35_loss: 0.4126 - val_loss: 0.3415 - val_dense_36_loss: 0.3330 - val_dense_35_loss: 0.4178
Epoch 5/100
11610/11610 [==============================] - 1s 89us/sample - loss: 0.3372 - dense_36_los

In [109]:
class PrintValTrainRatioCallback (keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs):
        print("\nval/train: {:.2f}".format(logs["val_loss"]/logs["loss"]))