In [1]:
import tensorflow as tf
X=tf.range(10)

In [2]:
X

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [5]:
dataset=tf.data.Dataset.from_tensor_slices(X)

In [6]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [7]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [8]:
dataset=dataset.repeat(3).batch(7)

In [9]:
for item in dataset:
    print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [10]:
dataset= dataset.map(lambda x : x*2)

In [12]:
for item in dataset:
    print(item)

tf.Tensor([ 0  2  4  6  8 10 12], shape=(7,), dtype=int32)
tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)
tf.Tensor([ 2  4  6  8 10 12 14], shape=(7,), dtype=int32)
tf.Tensor([16 18], shape=(2,), dtype=int32)


In [14]:
dataset= dataset.apply(tf.data.experimental.unbatch())

Instructions for updating:
Use `tf.data.Dataset.unbatch()`.


In [15]:
dataset

<_UnbatchDataset shapes: (), types: tf.int32>

In [16]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, sh

In [17]:
dataset= dataset.filter(lambda x:x<10)

In [18]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


In [19]:
dataset= dataset.take(3)

In [20]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [21]:
dataset=tf.data.Dataset.range(10).repeat(3)

In [22]:
dataset=dataset.shuffle(buffer_size=5, seed=42)

In [23]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype

In [24]:
dataset=tf.data.Dataset.range(10)

In [25]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


In [26]:
dataset=dataset.shuffle(buffer_size=5, seed=42)

In [27]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)


In [34]:
import csv

with open('housing_data.csv', 'r') as f:
    line_num=0
    file_num=0
    for line in f:
        if (line_num+1) % 100 ==0:
            file_num+=1
            with open('my_train_{}.csv'.format(file_num), 'w', newline="") as c:
                thewriter=csv.writer(c, delimiter=',')
                thewriter.writerow(line)
                line_num+=1
                c.close()
        else:    
            with open('my_train_{}.csv'.format(file_num), 'w', newline="") as c:
                thewriter=csv.writer(c, delimiter=',')
                thewriter.writerow(line)
                line_num+=1
                c.close()

In [45]:
train_filepaths=['my_train_0.csv', 'my_train_1.csv', 'my_train_2.csv']

In [46]:
filepath_dataset = tf.data.Dataset.list_files(train_filepaths, seed=42)

In [47]:
n_readers=5
dataset=filepath_dataset.interleave( lambda filepath:tf.data.TextLineDataset(filepath).skip(1),
                                   cycle_length=n_readers)

In [48]:
for line in dataset.take(2):
    print(line.numpy())

b'-122.23,37.88,41,880,129,322,126,8.3252,452600'
b'-122.27,37.83,51,2665,574,1258,536,2.7303,109700'


In [54]:
X_mean= [-122.2536842,37.84842105,49.0,2237.526316,445.6315789,932.8421053,431.9473684,3.815521053,251842.1053]
X_std= [0.01265349,0.009874559,7.341303484,1426.421558,247.319144,500.7496762,252.3094328,2.027857296,88626.01683]

In [55]:
n_inputs=8

In [61]:
def preprocess(line):
    defs=[0.]*n_inputs+[tf.constant([],dtype=tf.float32)]
    fields= tf.io.decode_csv(line, record_defaults=defs)
    x = tf.stack(fields[:-1])
    y = tf.stack(fields[-1:])
    return (x-X_mean) /X_std, y

In [60]:
preprocess(b'-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0')

InvalidArgumentError: Expect 9 fields but have 8 in record 0 [Op:DecodeCSV]

In [66]:
def csv_reader_dataset(filepaths, repeat=1, n_readers=5, n_read_threads=None, shuffle_buffer_size=10000, 
                      n_parse_threads=5, batch_size=32):
    dataset=tf.data.Dataset.list_files(filepaths)
    dataset=dataset.interleave(lambda filepath: tf.data.TextLineDataset(filepath).skip(1),
                              cycle_length=n_readers, num_parallel_calls=n_read_threads)
    dataset=dataset.map(preprocess, num_parallel_calls=n_parse_threads)
    dataset=dataset.shuffle(shuffle_buffer_size).repeat(repeat)
    return dataset.batch(batch_size).prefetch(1)

In [67]:
train_filepaths=['my_train_0.csv', 'my_train_1.csv', 'my_train_2.csv']
valid_filepaths=['my_train_0.csv', 'my_train_1.csv', 'my_train_2.csv']
test_filepaths=['my_train_0.csv', 'my_train_1.csv', 'my_train_2.csv']

In [68]:
train_set=csv_reader_dataset(train_filepaths)
valid_set=csv_reader_dataset(valid_filepaths)
test_set=csv_reader_dataset(test_filepaths)

ValueError: in converted code:

    <ipython-input-61-489549dffbf3>:6 preprocess  *
        return (x-X_mean) /X_std, y
    C:\Users\keonhi\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\math_ops.py:915 binary_op_wrapper
        return func(x, y, name=name)
    C:\Users\keonhi\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py:10103 sub
        "Sub", x=x, y=y, name=name)
    C:\Users\keonhi\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\op_def_library.py:742 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    C:\Users\keonhi\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\func_graph.py:595 _create_op_internal
        compute_device)
    C:\Users\keonhi\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py:3322 _create_op_internal
        op_def=op_def)
    C:\Users\keonhi\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py:1786 __init__
        control_input_ops)
    C:\Users\keonhi\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py:1622 _create_c_op
        raise ValueError(str(e))

    ValueError: Dimensions must be equal, but are 8 and 9 for 'sub' (op: 'Sub') with input shapes: [8], [9].


In [70]:
from tensorflow import keras
model=keras.models.Sequential([])
model.compile([])
model.fit(train_set, epochs=10, validation_data=valid_Set)

NameError: name 'train_set' is not defined

In [71]:
model.evaluate(test_set)
new_set=test_set.take(3).map(lambda X, y : X)
model.predict(new_set)

NameError: name 'test_set' is not defined