In [1]:
import tensorflow as tf

In [2]:
from tensorflow import keras

In [3]:
X=tf.range(100)

In [4]:
dataset=tf.data.Dataset.from_tensor_slices(X)

In [5]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [6]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(17, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(19, shape=(), dtype=int32)
tf.Tensor(20, shape=(), dtype=int32)
tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(23, shape=(), dtype=int32)
tf.Tensor(24, shape=(), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(26, shape=(), dtype=int32)
tf.Tensor(2

In [7]:
dataset= dataset.repeat(3).batch(7)

In [9]:
for item in dataset:
    print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([ 7  8  9 10 11 12 13], shape=(7,), dtype=int32)
tf.Tensor([14 15 16 17 18 19 20], shape=(7,), dtype=int32)
tf.Tensor([21 22 23 24 25 26 27], shape=(7,), dtype=int32)
tf.Tensor([28 29 30 31 32 33 34], shape=(7,), dtype=int32)
tf.Tensor([35 36 37 38 39 40 41], shape=(7,), dtype=int32)
tf.Tensor([42 43 44 45 46 47 48], shape=(7,), dtype=int32)
tf.Tensor([49 50 51 52 53 54 55], shape=(7,), dtype=int32)
tf.Tensor([56 57 58 59 60 61 62], shape=(7,), dtype=int32)
tf.Tensor([63 64 65 66 67 68 69], shape=(7,), dtype=int32)
tf.Tensor([70 71 72 73 74 75 76], shape=(7,), dtype=int32)
tf.Tensor([77 78 79 80 81 82 83], shape=(7,), dtype=int32)
tf.Tensor([84 85 86 87 88 89 90], shape=(7,), dtype=int32)
tf.Tensor([91 92 93 94 95 96 97], shape=(7,), dtype=int32)
tf.Tensor([98 99  0  1  2  3  4], shape=(7,), dtype=int32)
tf.Tensor([ 5  6  7  8  9 10 11], shape=(7,), dtype=int32)
tf.Tensor([12 13 14 15 16 17 18], shape=(7,), dtype=int32)
tf.T

In [13]:
dataset=dataset.map(lambda x: x*2)
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)


In [15]:
dataset = dataset.apply(tf.data.experimental.unbatch())

ValueError: in converted code:

    C:\Users\keonhi\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py:1968 normalize
        return structure.to_batched_tensor_list(self.element_spec, arg)
    C:\Users\keonhi\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\data\util\structure.py:350 to_batched_tensor_list
        component), element_spec, element)
    C:\Users\keonhi\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\data\util\structure.py:324 _to_tensor_list_helper
        reduce_fn, zip(nest.flatten(element_spec), nest.flatten(element)), [])
    C:\Users\keonhi\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\data\util\structure.py:321 reduce_fn
        return encode_fn(state, spec, component)
    C:\Users\keonhi\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\data\util\structure.py:350 <lambda>
        component), element_spec, element)
    C:\Users\keonhi\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\type_spec.py:462 _to_batched_tensor_list
        raise ValueError("Value %s has insufficient rank for batching." % value)

    ValueError: Value Tensor("args_0:0", shape=(), dtype=int32) has insufficient rank for batching.


In [16]:
dataset = dataset.filter(lambda x: x<10)
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


In [17]:
for item in dataset.take(3):
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


In [18]:
dataset=tf.data.Dataset.range(10).repeat(3)

In [19]:
dataset=dataset.shuffle(buffer_size=5, seed=42).batch(7)

In [20]:
for item in dataset:
    print(item)

tf.Tensor([0 2 3 6 7 9 4], shape=(7,), dtype=int64)
tf.Tensor([5 0 1 1 8 6 5], shape=(7,), dtype=int64)
tf.Tensor([4 8 7 1 2 3 0], shape=(7,), dtype=int64)
tf.Tensor([5 4 2 7 8 9 9], shape=(7,), dtype=int64)
tf.Tensor([3 6], shape=(2,), dtype=int64)
